# Generated by Django 2.0 on 2018-02-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_zone_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['zone']},
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
