# Generated by Django 2.0 on 2018-02-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_old_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['first_name']},
        ),
    ]
