# Generated by Django 2.0 on 2018-02-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='contact',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='operations_phone_number',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
