# Generated by Django 2.0 on 2018-02-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
