# Generated by Django 2.0 on 2018-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_auto_20180218_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
