# Generated by Django 2.0 on 2018-02-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_auto_20180218_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financial',
            options={'ordering': ['status']},
        ),
    ]
