# Generated by Django 2.0 on 2018-02-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('driver', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('customer', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Zone')),
            ],
        ),
    ]
