# Generated by Django 2.0 on 2018-02-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_zone_description'),
        ('financials', '0002_auto_20180218_1440'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('update', models.TextField(blank=True, null=True)),
                ('financial_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.Financial')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount_dollars',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount_lebanese',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='financial_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financials.Financial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
