# Generated by Django 2.0 on 2018-02-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180222_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='actual_amount',
            new_name='actual_amount_lebanese',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_amount_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
