# Generated by Django 2.0 on 2018-02-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180222_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='actual_amount_lebanese',
            new_name='actual_lebanese',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='actual_amount_usd',
            new_name='actual_usd',
        ),
    ]
